/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.ia1;



/**
 *
 * @author rociopv
 */
public class contestForum extends javax.swing.JFrame {

    /**
     * Creates new form contestForum
     */
    int currentReport = 0;
    String[] titleReport;
    ForumReport report = new ForumReport();
    private void setReport(){
        if (titleReport.length!=0){
            /*String query = "SELECT * FROM ForumReports WHERE titleReport = ?"; 
            String[] parameters2 = {titleReport[currentReport]};
            String[] columnResults2 = {"bodyReport","userSubmitted","userVoted", "votesDelete", "votesKeep"};
            report.setForumReport(titleReport[currentReport]);
            String[] extracted = Common.SQLquery(query, parameters2, columnResults2, -1, null);
            titleReportLabel.setText(titleReport[currentReport] + " report. Reported by " + extracted[1]);
            bodyReport.setText(extracted[0]);
            Delete.setText("Delete - "+ extracted[3]);
            Keep.setText("Keep - "+ extracted[4]);*/
            report.setForumReport(titleReport[currentReport]);
            titleReportLabel.setText(titleReport[currentReport] + " report. Reported by " + report.getUserSubmitted());
            bodyReport.setText(report.getBody());
            Delete.setText("Delete - "+ report.getVotesDelete());
            Keep.setText("Keep - "+ report.getVotesKeep());
        }
        else{
            titleReportLabel.setText("no reports made yet");
            bodyReport.setText("");
            Delete.setText("Delete - 0");
            Keep.setText("Keep - 0");
        }
      
    }
    /*private void submitVote(String votesType){
        String query = "SELECT * FROM ForumReports WHERE titleReport = ?"; 
        String[] parameters = {titleReport[currentReport]};
        String[] columnResults = {votesType, "userVoted"};   
        String[] extracted = Common.SQLquery(query, parameters, columnResults, -1, null);
        
        if(extracted[1].contains(Common.currentUser)){
            updateLabel.setText("Vote already casted");
        }
        else {
            int votes = Integer.parseInt(extracted[0]);
            votes++;
            String votesUpdate = Integer.toString(votes);
            query = "UPDATE ForumReports SET "+ votesType + " = ?, userVoted = CONCAT(userVoted, ?) WHERE titleReport = ?";
            String[] parameter = {votesUpdate,Common.currentUser, titleReport[currentReport]};
            Common.SQLquery(query, parameter, null, -1,null);
            updateLabel.setText("Vote casted!");
            if(votesType.equals("votesKeep")){
                Keep.setText("Keep - "+ votesUpdate);
            }
            else{
                Delete.setText("Delete - "+ votesUpdate);
            }
        }
        query = "SELECT * FROM ForumReports WHERE titleReport = ?"; 
        String[] parameters2 = {titleReport[currentReport]};
        String[] columnResults2 = {"votesKeep", "votesDelete"};   
        extracted = Common.SQLquery(query, parameters2, columnResults2, -1, null);
        String pass = "yes";
        if (Integer.parseInt(extracted[0])<Integer.parseInt(extracted[1])){
            pass = "no";
        }
        query = "UPDATE ForumReports SET  pass=?  WHERE titleReport = ?";
        String[] parameters3 = {pass,titleReport[currentReport]};
        Common.SQLquery(query, parameters3, null,-1,null);
    }*/
    
    public contestForum() {
        initComponents();
        String query = "SELECT * FROM ForumReports WHERE contestID = ?"; 
        String[] parameters ={Common.contestID};
        String[] columnResults = {"titleReport"};   
        titleReport = Common.SQLquery(query, parameters, columnResults, -1, null);
        setReport();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        viewSubmissions = new javax.swing.JDialog();
        titles = new javax.swing.JComboBox<>();
        backDialog = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        imageDisplayer = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        newReport = new javax.swing.JDialog();
        titlesSubmissionsReport = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        bodyReportTextField = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        backReport = new javax.swing.JButton();
        submitReport = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        back = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        titleReportLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        bodyReport = new javax.swing.JTextArea();
        Keep = new javax.swing.JButton();
        Delete = new javax.swing.JButton();
        updateLabel = new javax.swing.JLabel();
        nextReport = new javax.swing.JButton();
        pastReport = new javax.swing.JButton();
        openNewReport = new javax.swing.JButton();

        viewSubmissions.setAlwaysOnTop(true);
        viewSubmissions.setMinimumSize(new java.awt.Dimension(1000, 600));

        titles.setBackground(new java.awt.Color(220, 239, 216));
        titles.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select submission" }));
        titles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                titlesActionPerformed(evt);
            }
        });

        backDialog.setText("back");
        backDialog.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backDialogActionPerformed(evt);
            }
        });

        jScrollPane1.setMinimumSize(new java.awt.Dimension(400, 800));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(400, 800));
        jScrollPane1.setSize(new java.awt.Dimension(600, 800));

        imageDisplayer.setMaximumSize(new java.awt.Dimension(800, 1200));
        imageDisplayer.setRequestFocusEnabled(false);
        jScrollPane1.setViewportView(imageDisplayer);

        jLabel5.setText("Select a submission to review for breaches of the contest's rules:");

        javax.swing.GroupLayout viewSubmissionsLayout = new javax.swing.GroupLayout(viewSubmissions.getContentPane());
        viewSubmissions.getContentPane().setLayout(viewSubmissionsLayout);
        viewSubmissionsLayout.setHorizontalGroup(
            viewSubmissionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewSubmissionsLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(backDialog)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addComponent(titles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(263, 263, 263))
            .addGroup(viewSubmissionsLayout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 735, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(143, Short.MAX_VALUE))
        );
        viewSubmissionsLayout.setVerticalGroup(
            viewSubmissionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(viewSubmissionsLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(viewSubmissionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(backDialog)
                    .addComponent(titles, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 466, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );

        newReport.setAlwaysOnTop(true);
        newReport.setMinimumSize(new java.awt.Dimension(800, 500));

        titlesSubmissionsReport.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setText("What submission do you want to report?");

        bodyReportTextField.setColumns(20);
        bodyReportTextField.setRows(5);
        jScrollPane3.setViewportView(bodyReportTextField);

        jLabel2.setText("Describe breach of rules, in detail ");

        jLabel3.setText("Remember that a report can disqualify a submission, report responsibly");

        backReport.setText("back");
        backReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backReportActionPerformed(evt);
            }
        });

        submitReport.setBackground(new java.awt.Color(220, 239, 216));
        submitReport.setText("Submit report");
        submitReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitReportActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout newReportLayout = new javax.swing.GroupLayout(newReport.getContentPane());
        newReport.getContentPane().setLayout(newReportLayout);
        newReportLayout.setHorizontalGroup(
            newReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newReportLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backReport)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newReportLayout.createSequentialGroup()
                .addContainerGap(165, Short.MAX_VALUE)
                .addGroup(newReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addGroup(newReportLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(newReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 438, Short.MAX_VALUE)
                            .addComponent(submitReport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(newReportLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(96, 96, 96)
                        .addComponent(titlesSubmissionsReport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(191, 191, 191))
        );
        newReportLayout.setVerticalGroup(
            newReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newReportLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backReport)
                .addGap(8, 8, 8)
                .addGroup(newReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(titlesSubmissionsReport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(28, 28, 28)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(newReportLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(submitReport)
                    .addComponent(jLabel4))
                .addContainerGap(63, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(800, 500));
        setMinimumSize(new java.awt.Dimension(800, 500));
        setPreferredSize(new java.awt.Dimension(800, 500));

        jPanel1.setBackground(new java.awt.Color(226, 202, 163));
        jPanel1.setMaximumSize(new java.awt.Dimension(800, 500));
        jPanel1.setMinimumSize(new java.awt.Dimension(800, 500));
        jPanel1.setSize(new java.awt.Dimension(800, 500));

        back.setText("back");
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "forum", "view submissions" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        titleReportLabel.setText("Report Title");

        bodyReport.setColumns(20);
        bodyReport.setRows(5);
        jScrollPane2.setViewportView(bodyReport);

        Keep.setBackground(new java.awt.Color(220, 239, 216));
        Keep.setText("Keep");
        Keep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KeepActionPerformed(evt);
            }
        });

        Delete.setBackground(new java.awt.Color(200, 60, 60));
        Delete.setText("Delete");
        Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DeleteActionPerformed(evt);
            }
        });

        updateLabel.setText(" ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titleReportLabel)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(Delete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(updateLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Keep)
                .addGap(58, 58, 58))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(titleReportLabel)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Keep)
                    .addComponent(Delete)
                    .addComponent(updateLabel))
                .addContainerGap())
        );

        nextReport.setText(">");
        nextReport.setMaximumSize(new java.awt.Dimension(50, 23));
        nextReport.setMinimumSize(new java.awt.Dimension(50, 23));
        nextReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextReportActionPerformed(evt);
            }
        });

        pastReport.setText("<");
        pastReport.setMaximumSize(new java.awt.Dimension(50, 23));
        pastReport.setMinimumSize(new java.awt.Dimension(50, 23));
        pastReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pastReportActionPerformed(evt);
            }
        });

        openNewReport.setBackground(new java.awt.Color(220, 239, 216));
        openNewReport.setText("Make new report");
        openNewReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openNewReportActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(back))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(153, 153, 153)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(pastReport, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(nextReport, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(openNewReport, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(31, 31, 31))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(back)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(openNewReport)))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(pastReport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nextReport, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(63, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        if("view submissions".equals(String.valueOf(jComboBox1.getSelectedItem()))){
            viewSubmissions.setVisible(true);
            String query = "SELECT * FROM Submissions WHERE contestID = ?"; 
            String[] parameters ={Common.contestID};
            String[] columnResults = {"title"};
            
            String[] extracted = Common.SQLquery(query, parameters, columnResults,  -1, null);
            titles.setModel(new javax.swing.DefaultComboBoxModel<>(extracted));
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void titlesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_titlesActionPerformed
        
        /*String query = "SELECT * FROM Submissions WHERE title = ?"; 
        int[] dimensions = {800,500};
        String[] parameters ={String.valueOf(titles.getSelectedItem())};
        String[] columnResults = {"document"};
        String[] extracted = Common.SQLquery(query, parameters, columnResults, -1, null);
        byte[] extract = Base64.getDecoder().decode(extracted[0]);
        ByteArrayInputStream bis = new ByteArrayInputStream(extract);
        try {
            dimensions = Common.resizeProportionally( ImageIO.read(bis), 800, 1000) ;
        } catch (IOException ex) {
            Logger.getLogger(contestForum.class.getName()).log(Level.SEVERE, null, ex);
        }
        ImageIcon image = new ImageIcon(extract);
        Image img = image.getImage();
        System.out.println("dimensions" + dimensions[0]+ dimensions[1]);
        Image scaledImg = img.getScaledInstance(dimensions[0], dimensions[1],Image.SCALE_SMOOTH);
        ImageIcon newImage = new ImageIcon(scaledImg);*/
        Submissions submission = new Submissions(String.valueOf(titles.getSelectedItem()));
        imageDisplayer.setIcon(submission.displaySubmission(800,500));
    }//GEN-LAST:event_titlesActionPerformed

    private void backDialogActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backDialogActionPerformed
        viewSubmissions.setVisible(false);
    }//GEN-LAST:event_backDialogActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        this.setVisible(false);
        new Menu().setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    private void openNewReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openNewReportActionPerformed
        newReport.setVisible(true);
        String query = "SELECT * FROM Submissions WHERE contestID = ?"; 
        String[] parameters ={Common.contestID};
        String[] columnResults = {"title"};   
        String[] extracted = Common.SQLquery(query, parameters, columnResults, -1, null);
        titlesSubmissionsReport.setModel(new javax.swing.DefaultComboBoxModel<>(extracted));
    }//GEN-LAST:event_openNewReportActionPerformed

    private void backReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backReportActionPerformed
        newReport.setVisible(false);
    }//GEN-LAST:event_backReportActionPerformed

    private void submitReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitReportActionPerformed
        String statement = "INSERT INTO ForumReports (contestID,titleReport,bodyReport,userSubmitted,votesDelete,votesKeep) VALUES (?,?,?,?,?,?)";
        String[] parameters = {Common.contestID, String.valueOf(titlesSubmissionsReport.getSelectedItem()), String.valueOf(bodyReportTextField.getText()),Common.currentUser,"0","0"};
        Common.SQLquery(statement, parameters, -1, null);
        jLabel4.setText("Report sent, screen will close soon!");  
        newReport.setVisible(false);
    }//GEN-LAST:event_submitReportActionPerformed

    private void nextReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextReportActionPerformed
        if(titleReport.length > currentReport+1){
            currentReport++;
            setReport();
        }
    }//GEN-LAST:event_nextReportActionPerformed

    private void pastReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pastReportActionPerformed
        if(currentReport-1>=0){
            currentReport--;
            setReport();
        }
    }//GEN-LAST:event_pastReportActionPerformed

    private void KeepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KeepActionPerformed
        //submitVote("votesKeep");
        if(report.setVoteKeep()){
        
            Keep.setText("Keep - "+ report.getVotesKeep());
            updateLabel.setText("Vote casted!");
        }
        else{
            updateLabel.setText("You already voted"); 
        }
        report.setPass();
    }//GEN-LAST:event_KeepActionPerformed

    private void DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DeleteActionPerformed
        //submitVote("votesDelete");
         if(report.setVoteDelete()){
            Delete.setText("Delete - "+ report.getVotesDelete());
            updateLabel.setText("Vote casted!");
        }
        else{
            updateLabel.setText("You already voted"); 
        }
        report.setPass();
    }//GEN-LAST:event_DeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(contestForum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(contestForum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(contestForum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(contestForum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new contestForum().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Delete;
    private javax.swing.JButton Keep;
    private javax.swing.JButton back;
    private javax.swing.JButton backDialog;
    private javax.swing.JButton backReport;
    private javax.swing.JTextArea bodyReport;
    private javax.swing.JTextArea bodyReportTextField;
    private javax.swing.JLabel imageDisplayer;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JDialog newReport;
    private javax.swing.JButton nextReport;
    private javax.swing.JButton openNewReport;
    private javax.swing.JButton pastReport;
    private javax.swing.JButton submitReport;
    private javax.swing.JLabel titleReportLabel;
    private javax.swing.JComboBox<String> titles;
    private javax.swing.JComboBox<String> titlesSubmissionsReport;
    private javax.swing.JLabel updateLabel;
    private javax.swing.JDialog viewSubmissions;
    // End of variables declaration//GEN-END:variables
}
