/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.ia1;

import java.awt.Image;
import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.time.LocalDate;
import java.util.Arrays;
import java.util.Base64;
import java.util.HashSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;

/**
 *
 * @author rociopv
 */
public class In extends javax.swing.JFrame {

    /**
     * Creates new form In
     */
    int numContest = 0;
    String[] nameContest = null;
    public In() {
        initComponents();
        common.updateStatus(); 
        presidentOnly.setVisible(common.isPresident());
        presidentOnly.enableInputMethods(common.isPresident());
        emergency.setVisible(common.isPresident());
        emergency.enableInputMethods(common.isPresident());
        nameContest = DisplayContest(String.valueOf(currentStatus.getSelectedItem()));
        System.out.println("NAME CONTEST "+ Arrays.toString(nameContest));
        if(nameContest.length>0){
            displayedContest.setText(nameContest[numContest]);
        }
        else{
            displayedContest.setText("No contests in this state currently");
        }
 
        
       
            
        
       
    }
    private String[] DisplayContest(String statusToDisplay){
        String query = "SELECT * FROM Contests WHERE status = ?";
        String[] answers = null;
        String[] parameters = {statusToDisplay};
        String[] columnResults = {"name","id"};
        answers = common.SQLquery(query, parameters, columnResults, -1,null);
        return answers;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        newContestDialog = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        CurrentDate = new javax.swing.JLabel();
        subStart = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        forumStarts = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        contestName = new javax.swing.JTextField();
        submissionNumber = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        votesNumber = new javax.swing.JComboBox<>();
        votingEnds = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        linkRules = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        votingStarts = new javax.swing.JFormattedTextField();
        CreateContestButton = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        confirmation = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        ConfirmationNameOfContest = new javax.swing.JLabel();
        ConfirmationSubStarts = new javax.swing.JLabel();
        ConfirmationForumStarts = new javax.swing.JLabel();
        ConfirmationVotingStarts = new javax.swing.JLabel();
        ConfirmationVotingEnds = new javax.swing.JLabel();
        ConfirmationSubmissions = new javax.swing.JLabel();
        ConfirmationVotes = new javax.swing.JLabel();
        ConfirmationRulesLink = new javax.swing.JLabel();
        CreateContest = new javax.swing.JButton();
        closeConfirmation = new javax.swing.JButton();
        emergencyState = new javax.swing.JDialog();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        submission1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        submission2 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        submissionB2 = new javax.swing.JButton();
        submissionB1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        presidentOnly = new javax.swing.JButton();
        next = new javax.swing.JToggleButton();
        back = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        currentStatus = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        displayedContest = new javax.swing.JButton();
        LogOut = new javax.swing.JButton();
        emergency = new javax.swing.JButton();

        newContestDialog.setAlwaysOnTop(true);
        newContestDialog.setBackground(new java.awt.Color(226, 202, 163));
        newContestDialog.setMinimumSize(new java.awt.Dimension(800, 500));
        newContestDialog.setSize(new java.awt.Dimension(800, 500));

        jPanel3.setBackground(new java.awt.Color(226, 202, 163));
        jPanel3.setMaximumSize(new java.awt.Dimension(800, 500));
        jPanel3.setMinimumSize(new java.awt.Dimension(800, 500));
        jPanel3.setSize(new java.awt.Dimension(800, 500));

        subStart.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("d/M/yyyy"))));
        subStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subStartActionPerformed(evt);
            }
        });

        jLabel2.setText("Submission ends, Forum start date");

        jLabel3.setText("Forum end date, Voting begins");

        forumStarts.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("d/M/yyyy"))));
        forumStarts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forumStartsActionPerformed(evt);
            }
        });

        jLabel4.setText("Voting ends");

        jLabel6.setText("Format DD/MM/YYYY");

        jLabel7.setText("Format DD/MM/YYYY");

        contestName.setText("Name of contest");
        contestName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                contestNameMouseEntered(evt);
            }
        });
        contestName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contestNameActionPerformed(evt);
            }
        });

        submissionNumber.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));

        jLabel8.setText("Submission per person");

        votesNumber.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10" }));
        votesNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                votesNumberActionPerformed(evt);
            }
        });

        votingEnds.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("d/M/yyyy"))));
        votingEnds.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                votingEndsActionPerformed(evt);
            }
        });

        jLabel9.setText("Votes per person");

        jLabel10.setText("Format DD/MM/YYYY");

        jLabel11.setText("Submissions start");

        jLabel12.setText("(Optional) Link for the rules of submission:");

        jLabel5.setText("Format DD/MM/YYYY");

        votingStarts.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter(new java.text.SimpleDateFormat("d/M/yyyy"))));
        votingStarts.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                votingStartsActionPerformed(evt);
            }
        });

        CreateContestButton.setText("Create Contest!");
        CreateContestButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateContestButtonActionPerformed(evt);
            }
        });

        jLabel13.setForeground(new java.awt.Color(255, 0, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(subStart, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel5))
                                .addGap(31, 31, 31)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel2)
                                    .addComponent(forumStarts, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(39, 39, 39)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                            .addComponent(votingStarts, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(73, 73, 73))
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addGap(22, 22, 22)))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(77, 77, 77)))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(votingEnds, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7)))
                            .addComponent(CurrentDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(36, 36, 36)
                                        .addComponent(submissionNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(votesNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(55, 55, 55)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                            .addComponent(jLabel12)
                                            .addGap(18, 18, 18)
                                            .addComponent(linkRules, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(CreateContestButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(contestName, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(CurrentDate, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(contestName, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel11)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(subStart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(forumStarts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(votingEnds, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(votingStarts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel10))
                .addGap(89, 89, 89)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(submissionNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel12)
                        .addComponent(linkRules, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(votesNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CreateContestButton))
                .addGap(29, 29, 29)
                .addComponent(jLabel13)
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout newContestDialogLayout = new javax.swing.GroupLayout(newContestDialog.getContentPane());
        newContestDialog.getContentPane().setLayout(newContestDialogLayout);
        newContestDialogLayout.setHorizontalGroup(
            newContestDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        newContestDialogLayout.setVerticalGroup(
            newContestDialogLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newContestDialogLayout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        confirmation.setAlwaysOnTop(true);
        confirmation.setMinimumSize(new java.awt.Dimension(600, 400));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        ConfirmationNameOfContest.setText("Name of contest: ");

        ConfirmationSubStarts.setText("Submission start: ");

        ConfirmationForumStarts.setText("Submission ends, Forum starts: ");

        ConfirmationVotingStarts.setText("Forum ends, Voting starts: ");

        ConfirmationVotingEnds.setText("Voting ends: ");

        ConfirmationSubmissions.setText("Submissions per person: ");

        ConfirmationVotes.setText("Votes per person: ");

        ConfirmationRulesLink.setText("Link to rules: ");

        CreateContest.setBackground(new java.awt.Color(100, 254, 50));
        CreateContest.setText("Create Contest!!!");
        CreateContest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateContestActionPerformed(evt);
            }
        });

        closeConfirmation.setBackground(new java.awt.Color(255, 0, 55));
        closeConfirmation.setText("Need to edit");
        closeConfirmation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeConfirmationActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(ConfirmationRulesLink)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ConfirmationNameOfContest)
                            .addComponent(ConfirmationForumStarts)
                            .addComponent(ConfirmationVotingStarts)
                            .addComponent(ConfirmationVotingEnds)
                            .addComponent(ConfirmationSubmissions)
                            .addComponent(ConfirmationVotes)
                            .addComponent(ConfirmationSubStarts))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(closeConfirmation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CreateContest, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE))
                        .addGap(73, 73, 73))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(ConfirmationNameOfContest)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ConfirmationSubStarts)
                        .addGap(18, 18, 18)
                        .addComponent(ConfirmationForumStarts)
                        .addGap(18, 18, 18)
                        .addComponent(ConfirmationVotingStarts)
                        .addGap(18, 18, 18)
                        .addComponent(ConfirmationVotingEnds)
                        .addGap(18, 18, 18)
                        .addComponent(ConfirmationSubmissions)
                        .addGap(18, 18, 18)
                        .addComponent(ConfirmationVotes)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(CreateContest, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(ConfirmationRulesLink)
                .addGap(18, 18, 18)
                .addComponent(closeConfirmation)
                .addContainerGap(74, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout confirmationLayout = new javax.swing.GroupLayout(confirmation.getContentPane());
        confirmation.getContentPane().setLayout(confirmationLayout);
        confirmationLayout.setHorizontalGroup(
            confirmationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        confirmationLayout.setVerticalGroup(
            confirmationLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(confirmationLayout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        emergencyState.setAlwaysOnTop(true);

        jPanel5.setBackground(new java.awt.Color(226, 202, 163));

        submission1.setText("jLabel14");
        jScrollPane1.setViewportView(submission1);

        submission2.setText("jLabel16");
        jScrollPane2.setViewportView(submission2);

        jLabel14.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        jLabel14.setText("Tie breaker");

        submissionB2.setText("This one should win");
        submissionB2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submissionB2ActionPerformed(evt);
            }
        });

        submissionB1.setText("This one should win!");
        submissionB1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submissionB1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(340, 340, 340)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(354, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(submissionB1, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(submissionB2, javax.swing.GroupLayout.DEFAULT_SIZE, 347, Short.MAX_VALUE)
                    .addComponent(jScrollPane2))
                .addGap(39, 39, 39))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel14)
                .addGap(33, 33, 33)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(submissionB2)
                    .addComponent(submissionB1))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout emergencyStateLayout = new javax.swing.GroupLayout(emergencyState.getContentPane());
        emergencyState.getContentPane().setLayout(emergencyStateLayout);
        emergencyStateLayout.setHorizontalGroup(
            emergencyStateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        emergencyStateLayout.setVerticalGroup(
            emergencyStateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setMaximumSize(new java.awt.Dimension(800, 500));
        setMinimumSize(new java.awt.Dimension(800, 500));

        jPanel1.setBackground(new java.awt.Color(226, 202, 163));
        jPanel1.setMaximumSize(new java.awt.Dimension(800, 500));
        jPanel1.setMinimumSize(new java.awt.Dimension(800, 500));
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 500));
        jPanel1.setSize(new java.awt.Dimension(800, 500));

        presidentOnly.setBackground(new java.awt.Color(220, 239, 216));
        presidentOnly.setText("Edit contests");
        presidentOnly.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                presidentOnlyActionPerformed(evt);
            }
        });

        next.setText(">");
        next.setMaximumSize(new java.awt.Dimension(50, 23));
        next.setMinimumSize(new java.awt.Dimension(50, 23));
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });

        back.setText("<");
        back.setMaximumSize(new java.awt.Dimension(50, 23));
        back.setMinimumSize(new java.awt.Dimension(50, 23));
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setText("View contests that are in the state of:");

        currentStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "submission", "forum", "voting", "finished" }));
        currentStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                currentStatusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel1)
                .addGap(41, 41, 41)
                .addComponent(currentStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(jLabel15)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(currentStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        displayedContest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayedContestActionPerformed(evt);
            }
        });

        LogOut.setForeground(new java.awt.Color(200, 60, 60));
        LogOut.setText("Log Out");
        LogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LogOutActionPerformed(evt);
            }
        });

        emergency.setBackground(new java.awt.Color(200, 60, 60));
        emergency.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        emergency.setForeground(new java.awt.Color(255, 255, 255));
        emergency.setText("EMERGENCY VOTING");
        emergency.setToolTipText("");
        emergency.setMaximumSize(new java.awt.Dimension(107, 23));
        emergency.setMinimumSize(new java.awt.Dimension(107, 23));
        emergency.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emergencyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(emergency, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(presidentOnly, javax.swing.GroupLayout.DEFAULT_SIZE, 204, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(LogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(239, 239, 239)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(next, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(displayedContest, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(277, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(presidentOnly, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LogOut))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(emergency, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                .addComponent(displayedContest, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(next, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(back, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void presidentOnlyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_presidentOnlyActionPerformed
        newContestDialog.setVisible(true);
        LocalDate currentDate = LocalDate.now();      
        CurrentDate.setText("The current date and time is: "+ String.valueOf(currentDate)); 
    }//GEN-LAST:event_presidentOnlyActionPerformed

    private void votingEndsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_votingEndsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_votingEndsActionPerformed

    private void contestNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contestNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contestNameActionPerformed

    private void forumStartsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forumStartsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_forumStartsActionPerformed

    private void subStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subStartActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_subStartActionPerformed

    private void votingStartsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_votingStartsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_votingStartsActionPerformed

    private void CreateContestButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateContestButtonActionPerformed
        
        if(common.validDates(subStart.getText(),forumStarts.getText(),votingStarts.getText(),votingEnds.getText())){
        jLabel13.setText("Check that all the values are right before creating!");
        ConfirmationNameOfContest.setText("Name of contest: " + contestName.getText());
        ConfirmationSubStarts.setText("Submission start: " + subStart.getText());
        ConfirmationForumStarts.setText("Submission ends, Forum starts: "  + forumStarts.getText());
        ConfirmationVotingStarts.setText("Forum ends, Voting starts: " + votingStarts.getText());
        ConfirmationVotingEnds.setText("Voting ends: " + votingEnds.getText());
        ConfirmationSubmissions.setText("Submissions per person: " + submissionNumber.getSelectedItem().toString());
        ConfirmationVotes.setText("Votes per person: " + votesNumber.getSelectedItem().toString());
        ConfirmationRulesLink.setText("Link to rules: " + linkRules.getText());
        
        confirmation.setVisible(true);
        }
        else{
            jLabel13.setText("Oops, there seems to be a problem with the dates");
        }
    }//GEN-LAST:event_CreateContestButtonActionPerformed

    private void contestNameMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contestNameMouseEntered
        if (contestName.getText().equals("Name of contest")){
            contestName.setText("");
        }
    }//GEN-LAST:event_contestNameMouseEntered

    private void votesNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_votesNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_votesNumberActionPerformed

    private void CreateContestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateContestActionPerformed

        String query = "INSERT INTO Contests (name,maxVotes,maxSubmissions, "
                + "startSubmissions, startForum, startVoting, endVoting, status) VALUES (?,?,?,?,?,?,?,?)";
        String[] parameters = {contestName.getText(), votesNumber.getSelectedItem().toString(),votesNumber.getSelectedItem().toString()
        ,subStart.getText(),forumStarts.getText(),votingStarts.getText(),votingEnds.getText(), "submission" };
        common.SQLquery(query, parameters, null, -1,null);
        query = "SELECT * FROM Contests where name = ?, startSubmissions = ?";
        String[] Parameter = {contestName.getText(), subStart.getText()};
        String[] columnResults2 = {"id"};
        String[] data = common.SQLquery(query, Parameter, columnResults2, -1,null);
        query = "INSERT INTO VotesperContest(contestID, userVotes, userMaxVotes) VALUES (?,?,?)";
        String[] parameters2 = {data[0], "",votesNumber.getSelectedItem().toString()};
        common.SQLquery(query, parameters2, null, -1, null);
        confirmation.setVisible(false);
        newContestDialog.setVisible(false);
    }//GEN-LAST:event_CreateContestActionPerformed

    private void closeConfirmationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeConfirmationActionPerformed
        confirmation.setVisible(false);
    }//GEN-LAST:event_closeConfirmationActionPerformed

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
        if (nameContest.length > numContest+2){
            numContest+=2;
            displayedContest.setText(nameContest[numContest]);
        }
    }//GEN-LAST:event_nextActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        if (numContest-2>=0){
            numContest-=2;
            displayedContest.setText(nameContest[numContest]);
        }
    }//GEN-LAST:event_backActionPerformed

    private void currentStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_currentStatusActionPerformed
        numContest= 0;
        nameContest = DisplayContest(String.valueOf(currentStatus.getSelectedItem()));
        if(nameContest.length>0){
            displayedContest.setText(nameContest[numContest]);
        }
        else{
            displayedContest.setText("No contests in this state currently");
        }
        
        
    }//GEN-LAST:event_currentStatusActionPerformed

    private void displayedContestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayedContestActionPerformed
        String query = "SELECT * FROM Contests WHERE name = ?";
        String[] parameters = {String.valueOf(displayedContest.getText())};
        String[] columnResults = {"id"};
        String[] id = common.SQLquery(query, parameters, columnResults, -1,null);
        common.contestID = id[0];
        String status = String.valueOf(currentStatus.getSelectedItem());
        switch (status) {
            case "submission" -> new contestSubmission().setVisible(true);
            case "forum" -> new contestForum().setVisible(true);
            case "voting" -> new contestVoting().setVisible(true);
            case "finished" -> new contestDone().setVisible(true);
          
            default -> {
            }
        }
        this.setVisible(false);
    }//GEN-LAST:event_displayedContestActionPerformed

    private void LogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LogOutActionPerformed
        this.setVisible(false);
        new open().setVisible(true);
    }//GEN-LAST:event_LogOutActionPerformed

    private void emergencyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emergencyActionPerformed
        
        jLabel14.setText("Tie breaker for "+ DisplayContest("emergency")[0]);
          String query = "SELECT * FROM Submissions WHERE title = ? AND contestID = ?"; 
            int[] dimensions = {800,500};
           
            String[] columnResults = {"document"};
            String[] parameters = {common.tiedTitles[0],DisplayContest("emergency")[1]};
            String[] extracted = common.SQLquery(query, parameters, columnResults, -1, null);
            byte[] extract = Base64.getDecoder().decode(extracted[0]);
            ByteArrayInputStream bis = new ByteArrayInputStream(extract);
            try {
                dimensions = common.reziseProportionally( ImageIO.read(bis), 800, 1000) ;
            } catch (IOException ex) {
                Logger.getLogger(contestForum.class.getName()).log(Level.SEVERE, null, ex);
            }
            ImageIcon image = new ImageIcon(extract);
            Image img = image.getImage();
            System.out.println("dimensions" + dimensions[0]+ dimensions[1]);
            Image scaledImg = img.getScaledInstance(dimensions[0], dimensions[1],Image.SCALE_SMOOTH);
            ImageIcon newImage = new ImageIcon(scaledImg);
            submission1.setIcon(newImage);
            String[] columnResults2 = {"document"};
            String[] parameters2 = {common.tiedTitles[1],DisplayContest("emergency")[1]};
            String[] extracted2 = common.SQLquery(query, parameters2, columnResults2, -1, null);
            byte[] extract2 = Base64.getDecoder().decode(extracted2[0]);
            ByteArrayInputStream bis2 = new ByteArrayInputStream(extract2);
            try {
                dimensions = common.reziseProportionally( ImageIO.read(bis2), 800, 1000) ;
            } catch (IOException ex) {
                Logger.getLogger(contestForum.class.getName()).log(Level.SEVERE, null, ex);
            }
            ImageIcon image2 = new ImageIcon(extract);
            Image img2 = image2.getImage();
            System.out.println("dimensions" + dimensions[0]+ dimensions[1]);
            Image scaledImg2 = img2.getScaledInstance(dimensions[0], dimensions[1],Image.SCALE_SMOOTH);
            ImageIcon newImage2 = new ImageIcon(scaledImg2);
            submission2.setIcon(newImage2);
          emergencyState.setVisible(true);
    }//GEN-LAST:event_emergencyActionPerformed

    private void submissionB1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submissionB1ActionPerformed
        String query =  "SELECT * FROM VotesperSubmission WHERE titleSubmission = ? AND contestID = ?";
        String[] columnResults = {"votes"};
        String[] parameters = {common.tiedTitles[0] , DisplayContest("emergency")[1]};
        String[] stringVotes = common.SQLquery(query, parameters, columnResults, -1, null);
        int votes = Integer.parseInt(stringVotes[0]);
        votes++;
        stringVotes[0] = Integer.toString(votes);
        query = "UPDATE VotesperSubmission SET votes= ? WHERE titleSubmission = ? AND contestID = ?";
        String[] parameter2 = {stringVotes[0],common.tiedTitles[0] , DisplayContest("emergency")[1]};
        common.SQLquery(query, parameter2, -1, null);
        query = "UPDATE Contests SET status = ? WHERE name = ? ";
        String[] parameters2 = {"voting", DisplayContest("emergency")[0]};
        common.SQLquery(query, parameters2, -1, null);
        emergencyState.setVisible(false);
    }//GEN-LAST:event_submissionB1ActionPerformed

    private void submissionB2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submissionB2ActionPerformed
        String query =  "SELECT * FROM VotesperSubmission WHERE titleSubmission = ? AND contestID = ?";
        String[] columnResults = {"votes"};
        String[] parameters = {common.tiedTitles[1] , DisplayContest("emergency")[1]};
        String[] stringVotes = common.SQLquery(query, parameters, columnResults, -1, null);
        int votes = Integer.parseInt(stringVotes[0]);
        votes++;
        stringVotes[0] = Integer.toString(votes);
        query = "UPDATE VotesperSubmission SET votes= ? WHERE titleSubmission = ? AND contestID = ?";
        String[] parameter2 = {stringVotes[0], common.tiedTitles[1] , DisplayContest("emergency")[1]};
        common.SQLquery(query, parameter2, -1, null);
        query = "UPDATE Contests SET status = ? WHERE name = ? ";
        String[] parameters2 = {"voting", DisplayContest("emergency")[0]};
        common.SQLquery(query, parameters2, -1, null);
        emergencyState.setVisible(false);
    }//GEN-LAST:event_submissionB2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(In.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(In.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(In.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(In.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new In().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ConfirmationForumStarts;
    private javax.swing.JLabel ConfirmationNameOfContest;
    private javax.swing.JLabel ConfirmationRulesLink;
    private javax.swing.JLabel ConfirmationSubStarts;
    private javax.swing.JLabel ConfirmationSubmissions;
    private javax.swing.JLabel ConfirmationVotes;
    private javax.swing.JLabel ConfirmationVotingEnds;
    private javax.swing.JLabel ConfirmationVotingStarts;
    private javax.swing.JButton CreateContest;
    private javax.swing.JButton CreateContestButton;
    private javax.swing.JLabel CurrentDate;
    private javax.swing.JButton LogOut;
    private javax.swing.JButton back;
    private javax.swing.JButton closeConfirmation;
    private javax.swing.JDialog confirmation;
    private javax.swing.JTextField contestName;
    private javax.swing.JComboBox<String> currentStatus;
    private javax.swing.JButton displayedContest;
    private javax.swing.JButton emergency;
    private javax.swing.JDialog emergencyState;
    private javax.swing.JFormattedTextField forumStarts;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField linkRules;
    private javax.swing.JDialog newContestDialog;
    private javax.swing.JToggleButton next;
    private javax.swing.JButton presidentOnly;
    private javax.swing.JFormattedTextField subStart;
    private javax.swing.JLabel submission1;
    private javax.swing.JLabel submission2;
    private javax.swing.JButton submissionB1;
    private javax.swing.JButton submissionB2;
    private javax.swing.JComboBox<String> submissionNumber;
    private javax.swing.JComboBox<String> votesNumber;
    private javax.swing.JFormattedTextField votingEnds;
    private javax.swing.JFormattedTextField votingStarts;
    // End of variables declaration//GEN-END:variables
}
